function Grav_Joint_Sp = Grav_leg(in1,in2)
%Grav_leg
%    Grav_Joint_Sp = Grav_leg(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    02-Nov-2023 00:24:46

b = in2(17,:);
g = in2(30,:);
lU = in2(28,:);
l_AC = in2(15,:);
l_A_m3 = in2(20,:);
l_B_m2 = in2(19,:);
l_C_m4 = in2(21,:);
l_OA = in2(13,:);
l_OB = in2(14,:);
l_O_m1 = in2(18,:);
l_cb = in2(22,:);
m1 = in2(1,:);
m2 = in2(2,:);
m3 = in2(3,:);
m4 = in2(4,:);
mU = in2(26,:);
ma = in2(5,:);
mb = in2(6,:);
phiU = in2(29,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
t2 = cos(th5);
t3 = l_AC.*m4;
t4 = l_A_m3.*m3;
t5 = l_B_m2.*m2;
t6 = th1+th5;
t7 = th3+th5;
t8 = sin(t6);
t9 = sin(t7);
t10 = t6+th2;
t11 = t7+th4;
t29 = t3+t4+t5;
t12 = sin(t10);
t13 = sin(t11);
t14 = l_C_m4.*m4.*t8;
t15 = l_C_m4.*m4.*t9;
t16 = l_OA.*m3.*t8;
t17 = l_OA.*m4.*t8;
t18 = l_OA.*m3.*t9;
t19 = l_OA.*m4.*t9;
t20 = l_O_m1.*m1.*t8;
t21 = l_O_m1.*m1.*t9;
t28 = l_OB.*m2.*t8.*2.0;
t22 = t3.*t12;
t23 = t3.*t13;
t24 = t4.*t12;
t25 = t4.*t13;
t26 = t5.*t12;
t27 = t5.*t13;
Grav_Joint_Sp = [-g.*(t14+t16+t17+t20+t22+t24+t26+t28);-g.*t12.*t29;-g.*(t15+t18+t19+t21+t23+t25+t27);-g.*t13.*t29;-g.*(t14+t15+t16+t17+t18+t19+t20+t21+t22+t23+t24+t25+t26+t27+t28+b.*m1.*t2.*2.0+b.*m2.*t2.*2.0+b.*m3.*t2.*2.0+b.*m4.*t2.*2.0-l_cb.*mb.*t2-lU.*mU.*cos(phiU+th5));0.0;-g.*(m1.*2.0+m2.*2.0+m3.*2.0+m4.*2.0-mU-ma-mb);0.0];
end
