function dJ = jacobian_dot_feet(in1,in2)
%JACOBIAN_DOT_FEET
%    dJ = JACOBIAN_DOT_FEET(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    02-Nov-2023 00:24:46

b = in2(17,:);
dth1 = in1(9,:);
dth2 = in1(10,:);
dth3 = in1(11,:);
dth4 = in1(12,:);
dth5 = in1(13,:);
l_AC = in2(15,:);
l_DE = in2(16,:);
l_OB = in2(14,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
t2 = cos(th5);
t3 = th1+th5;
t4 = th3+th5;
t5 = b.*t2;
t6 = cos(t3);
t7 = sin(t3);
t8 = sin(t4);
t9 = t3+th2;
t10 = t4+th4;
t11 = cos(t9);
t12 = sin(t9);
t13 = sin(t10);
t14 = l_DE.*t6;
t15 = l_OB.*t6;
t16 = l_DE.*t7;
t17 = l_DE.*t8;
t18 = l_OB.*t7;
t19 = l_OB.*t8;
t20 = l_AC.*t11;
t21 = l_AC.*t12;
t22 = l_AC.*t13;
t23 = dth2.*t20;
t24 = dth2.*t21;
t25 = dth4.*t22;
t27 = t14+t15+t20;
t28 = t16+t18+t21;
t29 = t17+t19+t22;
t26 = -t25;
t30 = dth1.*t28;
t31 = dth3.*t29;
t32 = dth1.*t27;
t33 = -t31;
dJ = reshape([t24+t30+dth5.*t28,t23+t32+dth5.*t27,0.0,0.0,t24+dth1.*t21+dth5.*t21,t23+dth1.*t20+dth5.*t20,0.0,0.0,0.0,0.0,0.0,t26+t33-dth5.*t29,0.0,0.0,0.0,t26-dth3.*t22-dth5.*t22,t24+t30-dth5.*(t5-t28),t23+t32+dth5.*(t27-b.*sin(th5)),0.0,t26+t33-dth5.*(t5+t29),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,8]);
end
