function keypoints = keypoints_leggedWheelchair(in1,in2)
%keypoints_leggedWheelchair
%    KEYPOINTS = keypoints_leggedWheelchair(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    31-Oct-2023 21:50:53

b = in2(16,:);
l1 = in2(14,:);
l2 = in2(15,:);
lU = in2(1,:);
phiU = in2(2,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
x = in1(6,:);
y = in1(7,:);
t2 = cos(th5);
t3 = sin(th5);
t4 = phiU+th5;
t5 = th1+th5;
t6 = th3+th5;
t7 = b.*t2;
t8 = b.*t3;
t9 = cos(t5);
t10 = cos(t6);
t11 = sin(t5);
t12 = sin(t6);
t13 = t5+th2;
t14 = t6+th4;
t15 = l1.*t9;
t16 = l1.*t10;
t17 = l1.*t11;
t18 = l1.*t12;
t19 = -t15;
t20 = -t16;
keypoints = reshape([x,y,t7+x,t8+y,t7+t17+x,t8+t19+y,t7+t18+x,t8+t20+y,t7+t17+x+l2.*sin(t13),t8+t19+y-l2.*cos(t13),t7+t18+x+l2.*sin(t14),t8+t20+y-l2.*cos(t14),x+lU.*cos(t4),y+lU.*sin(t4)],[2,7]);
