function rFeet = position_feet(in1,in2)
%POSITION_FEET
%    rFeet = POSITION_FEET(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
%    31-Oct-2023 20:27:20

b = in2(16,:);
l1 = in2(14,:);
l2 = in2(15,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
x = in1(6,:);
y = in1(7,:);
t2 = cos(th5);
t3 = sin(th5);
t4 = th1+th5;
t5 = th3+th5;
t6 = b.*t2;
t7 = b.*t3;
t8 = t4+th2;
t9 = t5+th4;
rFeet = reshape([t6+x+l1.*sin(t4)+l2.*sin(t8),t7+y-l1.*cos(t4)-l2.*cos(t8),t6+x+l1.*sin(t5)+l2.*sin(t9),t7+y-l1.*cos(t5)-l2.*cos(t9)],[2,2]);
