function rWheel = position_wheel(in1,in2)
%POSITION_WHEEL
%    rWheel = POSITION_WHEEL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
<<<<<<< HEAD
%    14-Nov-2023 17:39:25
=======
%    14-Nov-2023 15:06:23
>>>>>>> f3773e965c8bb7e7f53f909cecc54c0b17239d5c

r = in2(23,:);
x = in1(6,:);
y = in1(7,:);
rWheel = [x;-r+y];
