function drFeet = velocity_feet(in1,in2)
%VELOCITY_FEET
%    drFeet = VELOCITY_FEET(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    02-Nov-2023 00:24:44

b = in2(17,:);
dth1 = in1(9,:);
dth2 = in1(10,:);
dth3 = in1(11,:);
dth4 = in1(12,:);
dth5 = in1(13,:);
dx = in1(14,:);
dy = in1(15,:);
l_AC = in2(15,:);
l_DE = in2(16,:);
l_OB = in2(14,:);
th1 = in1(1,:);
th2 = in1(2,:);
th3 = in1(3,:);
th4 = in1(4,:);
th5 = in1(5,:);
t2 = cos(th5);
t3 = sin(th5);
t4 = th1+th5;
t5 = th3+th5;
t6 = b.*t2;
t7 = b.*t3;
t8 = cos(t4);
t9 = cos(t5);
t10 = sin(t4);
t11 = sin(t5);
t12 = t4+th2;
t13 = t5+th4;
t14 = cos(t12);
t15 = cos(t13);
t16 = sin(t12);
t17 = sin(t13);
t18 = l_DE.*t8;
t19 = l_DE.*t9;
t20 = l_OB.*t8;
t21 = l_OB.*t9;
t22 = l_DE.*t10;
t23 = l_DE.*t11;
t24 = l_OB.*t10;
t25 = l_OB.*t11;
t26 = l_AC.*t14;
t27 = l_AC.*t15;
t28 = l_AC.*t16;
t29 = l_AC.*t17;
drFeet = reshape([dx-dth2.*t26-dth1.*(t18+t20+t26)-dth5.*(t7+t18+t20+t26),dy+dth2.*t28+dth1.*(t22+t24+t28)+dth5.*(t6+t22+t24+t28),dx+dth4.*t27+dth5.*(-t7+t19+t21+t27)+dth3.*(t19+t21+t27),dy+dth4.*t29+dth3.*(t23+t25+t29)+dth5.*(t6+t23+t25+t29)],[2,2]);
end
