function drWheel = velocity_wheel(in1,in2)
%VELOCITY_WHEEL
%    drWheel = VELOCITY_WHEEL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.1.
<<<<<<< HEAD
%    14-Nov-2023 17:39:25
=======
%    14-Nov-2023 15:06:23
>>>>>>> f3773e965c8bb7e7f53f909cecc54c0b17239d5c

dx = in1(14,:);
dy = in1(15,:);
drWheel = [dx;dy];
